# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'switch_page_test.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(0, 0, 791, 541))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.stackedWidget = QtWidgets.QStackedWidget(self.gridLayoutWidget)
        self.stackedWidget.setObjectName("stackedWidget")
        self.page = QtWidgets.QWidget()
        self.page.setObjectName("page")
        self.label_2 = QtWidgets.QLabel(self.page)
        self.label_2.setGeometry(QtCore.QRect(190, 210, 211, 121))
        self.label_2.setObjectName("label_2")
        self.to_info_1 = QtWidgets.QPushButton(self.page)
        self.to_info_1.setGeometry(QtCore.QRect(510, 130, 93, 28))
        self.to_info_1.setObjectName("to_info_1")
        self.to_p2 = QtWidgets.QPushButton(self.page)
        self.to_p2.setGeometry(QtCore.QRect(510, 210, 93, 28))
        self.to_p2.setObjectName("to_p2")
        self.stackedWidget.addWidget(self.page)
        self.page_2 = QtWidgets.QWidget()
        self.page_2.setObjectName("page_2")
        self.to_info_2 = QtWidgets.QPushButton(self.page_2)
        self.to_info_2.setGeometry(QtCore.QRect(490, 120, 93, 28))
        self.to_info_2.setObjectName("to_info_2")
        self.label_3 = QtWidgets.QLabel(self.page_2)
        self.label_3.setGeometry(QtCore.QRect(220, 220, 201, 91))
        self.label_3.setObjectName("label_3")
        self.to_p1 = QtWidgets.QPushButton(self.page_2)
        self.to_p1.setGeometry(QtCore.QRect(490, 180, 93, 28))
        self.to_p1.setObjectName("to_p1")
        self.stackedWidget.addWidget(self.page_2)
        self.page_3 = QtWidgets.QWidget()
        self.page_3.setObjectName("page_3")
        self.label = QtWidgets.QLabel(self.page_3)
        self.label.setGeometry(QtCore.QRect(230, 200, 331, 131))
        font = QtGui.QFont()
        font.setFamily("Agency FB")
        font.setPointSize(26)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.back_button = QtWidgets.QPushButton(self.page_3)
        self.back_button.setGeometry(QtCore.QRect(590, 50, 171, 71))
        self.back_button.setObjectName("back_button")
        self.stackedWidget.addWidget(self.page_3)
        self.gridLayout.addWidget(self.stackedWidget, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.stackedWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_2.setText(_translate("MainWindow", "Page 1"))
        self.to_info_1.setText(_translate("MainWindow", "info..."))
        self.to_p2.setText(_translate("MainWindow", "goto p2"))
        self.to_info_2.setText(_translate("MainWindow", "info..."))
        self.label_3.setText(_translate("MainWindow", "Page 2"))
        self.to_p1.setText(_translate("MainWindow", "goto p1"))
        self.label.setText(_translate("MainWindow", "Personal info page"))
        self.back_button.setText(_translate("MainWindow", "Back"))
