# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'LOG_IN.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(1111, 845)
        self.ID_IN = QtWidgets.QTextEdit(Dialog)
        self.ID_IN.setGeometry(QtCore.QRect(380, 310, 371, 61))
        self.ID_IN.setObjectName("ID_IN")
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setGeometry(QtCore.QRect(330, 150, 531, 61))
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(21)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(Dialog)
        self.label_2.setGeometry(QtCore.QRect(330, 320, 81, 31))
        font = QtGui.QFont()
        font.setFamily("Bahnschrift SemiBold")
        font.setPointSize(17)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.PWD_IN = QtWidgets.QTextEdit(Dialog)
        self.PWD_IN.setGeometry(QtCore.QRect(380, 390, 371, 61))
        self.PWD_IN.setObjectName("PWD_IN")
        self.label_3 = QtWidgets.QLabel(Dialog)
        self.label_3.setGeometry(QtCore.QRect(300, 390, 121, 61))
        font = QtGui.QFont()
        font.setFamily("Bahnschrift SemiBold")
        font.setPointSize(17)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.LOG_IN = QtWidgets.QPushButton(Dialog)
        self.LOG_IN.setGeometry(QtCore.QRect(610, 580, 181, 61))
        font = QtGui.QFont()
        font.setFamily("Bahnschrift SemiBold")
        font.setPointSize(16)
        self.LOG_IN.setFont(font)
        self.LOG_IN.setObjectName("LOG_IN")
        self.CLEAR_ALL = QtWidgets.QPushButton(Dialog)
        self.CLEAR_ALL.setGeometry(QtCore.QRect(330, 580, 181, 61))
        font = QtGui.QFont()
        font.setFamily("Bahnschrift SemiBold")
        font.setPointSize(16)
        self.CLEAR_ALL.setFont(font)
        self.CLEAR_ALL.setObjectName("CLEAR_ALL")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.label.setText(_translate("Dialog", "LOG IN YOUR ACCOUNT"))
        self.label_2.setText(_translate("Dialog", "ID"))
        self.label_3.setText(_translate("Dialog", "PWD"))
        self.LOG_IN.setText(_translate("Dialog", "LOG IN"))
        self.CLEAR_ALL.setText(_translate("Dialog", "CLEAR ALL"))
